language: node_js
sudo: false

node_js:
  - "7.10.0"

cache:
  directories:
    - node_modules

os:
  - linux

script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true"
